// Generated by gen-pages.mjs — nav registry for the preview shell.
// Group shape mirrors react-uikit/preview/nav.ts (DEMO_GROUPS).
export const NAV = [
  {
    "title": "Layout",
    "routes": [
      {
        "slug": "layout",
        "title": "Layout",
        "page": "layout"
      },
      {
        "slug": "header",
        "title": "Header",
        "page": "header"
      },
      {
        "slug": "body",
        "title": "Body",
        "page": "body"
      },
      {
        "slug": "footer",
        "title": "Footer",
        "page": "footer"
      },
      {
        "slug": "sidebar",
        "title": "Sidebar",
        "page": "sidebar"
      },
      {
        "slug": "sidebartoggle",
        "title": "SidebarToggle",
        "page": "sidebartoggle"
      },
      {
        "slug": "row",
        "title": "Row",
        "page": "row"
      },
      {
        "slug": "column",
        "title": "Column",
        "page": "column"
      },
      {
        "slug": "stack",
        "title": "Stack",
        "page": "stack"
      },
      {
        "slug": "autogrid",
        "title": "AutoGrid",
        "page": "autogrid"
      }
    ]
  },
  {
    "title": "Typography",
    "routes": [
      {
        "slug": "text",
        "title": "Text",
        "page": "text"
      },
      {
        "slug": "icon",
        "title": "Icon",
        "page": "icon"
      }
    ]
  },
  {
    "title": "Buttons",
    "routes": [
      {
        "slug": "button",
        "title": "Button",
        "page": "button"
      },
      {
        "slug": "togglebutton",
        "title": "ToggleButton",
        "page": "togglebutton"
      },
      {
        "slug": "splitbutton",
        "title": "SplitButton",
        "page": "splitbutton"
      },
      {
        "slug": "fabmenu",
        "title": "FabMenu",
        "page": "fabmenu"
      }
    ]
  },
  {
    "title": "Forms",
    "routes": [
      {
        "slug": "form",
        "title": "Form",
        "page": "form"
      },
      {
        "slug": "field",
        "title": "Field",
        "page": "field"
      },
      {
        "slug": "fieldset",
        "title": "Fieldset",
        "page": "fieldset"
      },
      {
        "slug": "formfield",
        "title": "FormField",
        "page": "formfield"
      },
      {
        "slug": "input",
        "title": "Input",
        "page": "input"
      },
      {
        "slug": "textbox",
        "title": "TextBox",
        "page": "textbox"
      },
      {
        "slug": "textarea",
        "title": "TextArea",
        "page": "textarea"
      },
      {
        "slug": "password",
        "title": "Password",
        "page": "password"
      },
      {
        "slug": "mask",
        "title": "Mask",
        "page": "mask"
      },
      {
        "slug": "numeric",
        "title": "Numeric",
        "page": "numeric"
      },
      {
        "slug": "select",
        "title": "Select",
        "page": "select"
      },
      {
        "slug": "dropdown",
        "title": "DropDown",
        "page": "dropdown"
      },
      {
        "slug": "autocomplete",
        "title": "AutoComplete",
        "page": "autocomplete"
      },
      {
        "slug": "listbox",
        "title": "ListBox",
        "page": "listbox"
      },
      {
        "slug": "checkbox",
        "title": "CheckBox",
        "page": "checkbox"
      },
      {
        "slug": "checkboxlist",
        "title": "CheckBoxList",
        "page": "checkboxlist"
      },
      {
        "slug": "radiobuttonlist",
        "title": "RadioButtonList",
        "page": "radiobuttonlist"
      },
      {
        "slug": "switch",
        "title": "Switch",
        "page": "switch"
      },
      {
        "slug": "slider",
        "title": "Slider",
        "page": "slider"
      },
      {
        "slug": "rating",
        "title": "Rating",
        "page": "rating"
      },
      {
        "slug": "colorpicker",
        "title": "ColorPicker",
        "page": "colorpicker"
      },
      {
        "slug": "datepicker",
        "title": "DatePicker",
        "page": "datepicker"
      },
      {
        "slug": "timespanpicker",
        "title": "TimeSpanPicker",
        "page": "timespanpicker"
      },
      {
        "slug": "securitycode",
        "title": "SecurityCode",
        "page": "securitycode"
      },
      {
        "slug": "upload",
        "title": "Upload",
        "page": "upload"
      },
      {
        "slug": "dropzone",
        "title": "DropZone",
        "page": "dropzone"
      },
      {
        "slug": "signaturepad",
        "title": "SignaturePad",
        "page": "signaturepad"
      },
      {
        "slug": "selectbar",
        "title": "SelectBar",
        "page": "selectbar"
      },
      {
        "slug": "label",
        "title": "Label",
        "page": "label"
      }
    ]
  },
  {
    "title": "Feedback",
    "routes": [
      {
        "slug": "alert",
        "title": "Alert",
        "page": "alert"
      },
      {
        "slug": "progress",
        "title": "Progress",
        "page": "progress"
      },
      {
        "slug": "skeleton",
        "title": "Skeleton",
        "page": "skeleton"
      },
      {
        "slug": "emptystate",
        "title": "EmptyState",
        "page": "emptystate"
      },
      {
        "slug": "toast",
        "title": "Toast",
        "page": "toast"
      },
      {
        "slug": "dialog",
        "title": "Dialog",
        "page": "dialog"
      },
      {
        "slug": "contextmenu",
        "title": "ContextMenu",
        "page": "contextmenu"
      },
      {
        "slug": "tooltip",
        "title": "Tooltip",
        "page": "tooltip"
      },
      {
        "slug": "markdown",
        "title": "Markdown",
        "page": "markdown"
      }
    ]
  },
  {
    "title": "Navigation",
    "routes": [
      {
        "slug": "breadcrumb",
        "title": "Breadcrumb",
        "page": "breadcrumb"
      },
      {
        "slug": "link",
        "title": "Link",
        "page": "link"
      },
      {
        "slug": "menu",
        "title": "Menu",
        "page": "menu"
      },
      {
        "slug": "panelmenu",
        "title": "PanelMenu",
        "page": "panelmenu"
      },
      {
        "slug": "profilemenu",
        "title": "ProfileMenu",
        "page": "profilemenu"
      },
      {
        "slug": "tabs",
        "title": "Tabs",
        "page": "tabs"
      },
      {
        "slug": "steps",
        "title": "Steps",
        "page": "steps"
      },
      {
        "slug": "toc",
        "title": "Toc",
        "page": "toc"
      },
      {
        "slug": "pager",
        "title": "Pager",
        "page": "pager"
      }
    ]
  },
  {
    "title": "Data",
    "routes": [
      {
        "slug": "table",
        "title": "Table",
        "page": "table"
      },
      {
        "slug": "datagrid",
        "title": "DataGrid",
        "page": "datagrid"
      },
      {
        "slug": "datalist",
        "title": "DataList",
        "page": "datalist"
      },
      {
        "slug": "virtualgrid",
        "title": "VirtualGrid",
        "page": "virtualgrid"
      },
      {
        "slug": "tree",
        "title": "Tree",
        "page": "tree"
      },
      {
        "slug": "picklist",
        "title": "PickList",
        "page": "picklist"
      },
      {
        "slug": "pivot",
        "title": "Pivot",
        "page": "pivot"
      },
      {
        "slug": "chart",
        "title": "Chart",
        "page": "chart"
      },
      {
        "slug": "gauges",
        "title": "Gauges",
        "page": "gauges"
      },
      {
        "slug": "gantt",
        "title": "Gantt",
        "page": "gantt"
      },
      {
        "slug": "scheduler",
        "title": "Scheduler",
        "page": "scheduler"
      },
      {
        "slug": "timeline",
        "title": "Timeline",
        "page": "timeline"
      },
      {
        "slug": "datafilter",
        "title": "DataFilter",
        "page": "datafilter"
      },
      {
        "slug": "qrcode",
        "title": "QRCode",
        "page": "qrcode"
      },
      {
        "slug": "barcode",
        "title": "Barcode",
        "page": "barcode"
      }
    ]
  },
  {
    "title": "Display",
    "routes": [
      {
        "slug": "card",
        "title": "Card",
        "page": "card"
      },
      {
        "slug": "badge",
        "title": "Badge",
        "page": "badge"
      },
      {
        "slug": "avatar",
        "title": "Avatar",
        "page": "avatar"
      },
      {
        "slug": "stat",
        "title": "Stat",
        "page": "stat"
      },
      {
        "slug": "accordion",
        "title": "Accordion",
        "page": "accordion"
      },
      {
        "slug": "carousel",
        "title": "Carousel",
        "page": "carousel"
      },
      {
        "slug": "splitter",
        "title": "Splitter",
        "page": "splitter"
      }
    ]
  },
  {
    "title": "Theme",
    "routes": [
      {
        "slug": "themeswitcher",
        "title": "ThemeSwitcher",
        "page": "theme",
        "anchor": "themeswitcher"
      },
      {
        "slug": "themetoggle",
        "title": "ThemeToggle",
        "page": "theme",
        "anchor": "themetoggle"
      }
    ]
  },
  {
    "title": "Recipes",
    "routes": [
      {
        "slug": "recipe-login",
        "title": "Login split card",
        "page": "recipes",
        "anchor": "recipe-login"
      },
      {
        "slug": "recipe-404",
        "title": "Bare 404",
        "page": "recipes",
        "anchor": "recipe-404"
      }
    ]
  }
];
export const COMPONENT_COUNT = 86;
export function routeTitle(slug) {
  for (const g of NAV) for (const r of g.routes) if (r.slug === slug) return r.title;
  return slug === "" ? "htmx-uikit preview" : slug;
}
