#!/usr/bin/env node
/**
 * Build dist/uikit.js (bundled, minified behaviors) and dist/uikit.css
 * (the legacy alias layer + every component stylesheet, deterministic
 * order). Palette tokens are NOT bundled: consumers pair uikit.css with
 * any theme's tokens.css. The alias layer IS bundled — it defines the
 * flat names the utilities consume, so the utilities stay live however
 * the library is themed.
 *
 *   node scripts/build.mjs
 */

import { build } from "esbuild";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const LIB = join(ROOT, "lib");

const components = (await readdir(join(LIB, "components"), { withFileTypes: true }))
  .filter((e) => e.isDirectory())
  .map((e) => e.name)
  .sort();

await build({
  entryPoints: [join(LIB, "main.js")],
  bundle: true,
  format: "iife",
  minify: true,
  target: "es2020",
  outfile: join(ROOT, "dist/uikit.js"),
  banner: {
    js: "/* htmx-uikit behaviors — generated by scripts/build.mjs */",
  },
});

const cssParts = [join(LIB, "styles", "tokens.aliases.css")];
for (const name of components) {
  cssParts.push(join(LIB, "components", name, `${name}.css`));
}
const css = (
  await Promise.all(cssParts.map((p) => readFile(p, "utf8")))
).join("\n\n");
await mkdir(join(ROOT, "dist"), { recursive: true });
await writeFile(join(ROOT, "dist", "uikit.css"), css);

console.log(`built dist/uikit.js + dist/uikit.css (${components.length} components)`);